name: Generate GitHub Snake

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p dist

      - name: Generate GitHub Snake images
        uses: Platane/snk@v3
        with:
          github_user_name: Mummanajagadeesh
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=%23bfd6f6,%238dbdff,%2364a1f4,%234b91f1,%233c7dd9
          debug: true

      - name: Upload artifacts (optional)
        uses: github/upload-artifact@v1
        with:
          name: github-snake-images
          path: dist/
