name: Update README with Repo Cards

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"  # Runs daily at 12:00 UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Fetch repository metadata
        env:
          GH_TOKEN: ${{ secrets.PRIVATE_GH_TOKEN }}
        run: |
          QUERY='{"query":"query { user(login: \"Mummanajagadeesh\") { repository(name: \"ImProVe\") { name description stargazers { totalCount } } } }"}'
          RESPONSE=$(curl -s -H "Authorization: bearer $GH_TOKEN" \
            -H "Content-Type: application/json" \
            -X POST -d "$QUERY" https://api.github.com/graphql)
          echo "$RESPONSE" > repo.json

      - name: Generate SVG card and markdown
        run: |
          NAME=$(jq -r '.data.user.repository.name' repo.json)
          DESC=$(jq -r '.data.user.repository.description' repo.json)
          STARS=$(jq -r '.data.user.repository.stargazers.totalCount' repo.json)

          # Default fallback for empty description
          if [ "$DESC" = "null" ]; then DESC="No description provided"; fi

          # Create repos/ directory
          mkdir -p repos

          # Save SVG to repos/
          printf '%s\n' \
          '<svg width="400" height="120" viewBox="0 0 400 120" xmlns="http://www.w3.org/2000/svg">' \
          '  <style>' \
          '    .title { font: bold 18px sans-serif; fill: #0366d6; }' \
          '    .desc { font: 14px sans-serif; fill: #333; }' \
          '    .stars { font: 12px sans-serif; fill: #555; }' \
          '    .bg { fill: #f9f9f9; stroke: #e1e4e8; stroke-width: 1; }' \
          '  </style>' \
          '  <rect class="bg" x="0" y="0" width="400" height="120" rx="10"/>' \
          "  <text x=\"20\" y=\"35\" class=\"title\">$NAME</text>" \
          "  <text x=\"20\" y=\"60\" class=\"desc\">$DESC</text>" \
          "  <text x=\"20\" y=\"85\" class=\"stars\">⭐ $STARS stars</text>" \
          '</svg>' > repos/improve.svg

          # Create the markdown insertion block
          echo "<!--START:REPO_CARDS-->" > insert.txt
          echo "" >> insert.txt
          echo "<img src=\"./repos/improve.svg\" alt=\"$NAME repo card\" />" >> insert.txt
          echo "" >> insert.txt
          echo "<!--END:REPO_CARDS-->" >> insert.txt

      - name: Update README.md
        run: |
          awk '/<!--START:REPO_CARDS-->/ {print; system("tail -n +2 insert.txt | head -n -1"); found=1; next}
               /<!--END:REPO_CARDS-->/ {found=0}
               !found {print}' README.md > README.tmp
          mv README.tmp README.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md repos/improve.svg
          git commit -m "Update README with repo card" || echo "No changes to commit"
          git push
