name: Update README with Repo Cards

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"  # Runs every day at 12:00 UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y jq

      - name: Fetch repository metadata
        env:
          GH_TOKEN: ${{ secrets.PRIVATE_GH_TOKEN }}
        run: |
          QUERY='{"query":"query { user(login: \"Mummanajagadeesh\") { repository(name: \"ImProVe\") { name description isPrivate stargazers { totalCount } forkCount primaryLanguage { name color } } } }"}'
          RESPONSE=$(curl -s -H "Authorization: bearer $GH_TOKEN" -H "Content-Type: application/json" -X POST -d "$QUERY" https://api.github.com/graphql)
          echo "$RESPONSE" > repo.json

      - name: Generate SVG card
        run: |
          NAME=$(jq -r '.data.user.repository.name' repo.json)
          DESC=$(jq -r '.data.user.repository.description' repo.json)
          STARS=$(jq -r '.data.user.repository.stargazers.totalCount' repo.json)
          FORKS=$(jq -r '.data.user.repository.forkCount' repo.json)
          LANG=$(jq -r '.data.user.repository.primaryLanguage.name // "Unspecified"' repo.json)
          LANGCOLOR=$(jq -r '.data.user.repository.primaryLanguage.color // "#ccc"' repo.json)

          cat <<EOF > repo-card.svg
<svg width="400" height="140" viewBox="0 0 400 140" fill="none" xmlns="http://www.w3.org/2000/svg">
  <style>
    .header { font: bold 16px 'Segoe UI', sans-serif; fill: #0366d6; }
    .desc { font: normal 13px 'Segoe UI', sans-serif; fill: #333; }
    .stats { font: normal 12px 'Segoe UI', sans-serif; fill: #555; }
    .lang-dot { r: 6; }
  </style>
  <rect x="0" y="0" width="100%" height="100%" rx="10" fill="#f9f9f9" stroke="#e1e4e8"/>
  <text x="20" y="30" class="header">$NAME</text>
  <text x="20" y="55" class="desc">${DESC:-No description provided}</text>
  <circle cx="25" cy="95" r="6" fill="$LANGCOLOR" />
  <text x="40" y="100" class="stats">$LANG</text>
  <text x="150" y="100" class="stats">⭐ $STARS</text>
  <text x="230" y="100" class="stats">🍴 $FORKS</text>
</svg>
EOF

      - name: Insert SVG into README
        run: |
          echo "<!--START:REPO_CARDS-->" > insert.txt
          echo "" >> insert.txt
          echo '<p align="center">' >> insert.txt
          echo '<img src="repo-card.svg" alt="Repo Card" />' >> insert.txt
          echo '</p>' >> insert.txt
          echo "" >> insert.txt
          echo "<!--END:REPO_CARDS-->" >> insert.txt

          awk '/<!--START:REPO_CARDS-->/ {print; system("tail -n +2 insert.txt | head -n -1"); found=1; next}
               /<!--END:REPO_CARDS-->/ {found=0}
               !found {print}' README.md > README.tmp
          mv README.tmp README.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md repo-card.svg
          git commit -m "Update README with generated repo card" || echo "No changes to commit"
          git push
